apiVersion: v1
kind: Secret
metadata:
  name: go-cloud-secret
  namespace: go-cloud
type: Opaque
stringData:
  MYSQL_DSN: go_cloud:replace-me@tcp(mysql.go-cloud.svc.cluster.local:3306)/go_cloud?charset=utf8mb4&parseTime=True&loc=UTC
  REDIS_PASSWORD: ""
